const employeeListData = [
  {
    id: 1,
    name: "Alice Green",
    position: "Frontend Developer",
    rate: "$38/hour",
    period: "Monthly",
    workingHour: "145 hours",
    salary: "$5,510",
    status: "Active",
  },
  {
    id: 2,
    name: "Samantha Black",
    position: "UI/UX Designer",
    rate: "$37/hour",
    period: "Monthly",
    workingHour: "160 hours",
    salary: "$5,920",
    status: "Active",
  },
  {
    id: 3,
    name: "Michael Johnson",
    position: "Backend Developer",
    rate: "$40/hour",
    period: "Monthly",
    workingHour: "150 hours",
    salary: "$6,000",
    status: "Active",
  },
  {
    id: 4,
    name: "Emily White",
    position: "Project Manager",
    rate: "$50/hour",
    period: "Monthly",
    workingHour: "140 hours",
    salary: "$7,000",
    status: "Active",
  },
  {
    id: 5,
    name: "James Brown",
    position: "DevOps Engineer",
    rate: "$42/hour",
    period: "Monthly",
    workingHour: "155 hours",
    salary: "$6,510",
    status: "Inactive",
  },
  {
    id: 6,
    name: "Olivia Smith",
    position: "QA Engineer",
    rate: "$35/hour",
    period: "Monthly",
    workingHour: "160 hours",
    salary: "$5,600",
    status: "Active",
  },
  {
    id: 7,
    name: "William Davis",
    position: "Full Stack Developer",
    rate: "$45/hour",
    period: "Monthly",
    workingHour: "150 hours",
    salary: "$6,750",
    status: "Active",
  },
];

export default employeeListData;
